# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projectName: 'MyStationery'

steps:
- task: DotNetCoreCLI@2
  displayName: RestorePackages
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: VSTest@2
  displayName: RunTests
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'Stationery.UI'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'Stationery.UI'
    customCommand: 'run build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'Stationery.UI/build'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/mystationeryui.zip'
    replaceExistingArchive: true

- task: DotNetCoreCLI@2
  displayName: PublishProject
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
- task: PublishBuildArtifacts@1
  displayName: PushToContainer
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(projectName)'
    publishLocation: 'Container'

